### ISSUE TITLE
Add support for Ruby 2.1+

### ISSUE THREAD

**Issue by cyberarm** [Dahrkael/rENet#4]

**Comment by Dahrkael** [comment]
now it should be compatible

**Comment by cyberarm** [comment]
Fails to build on Windows 10 (x64), blows up on `win32.c`
Here are the [logs](https://gist.github.com/cyberarm/f8fe934cf14dac0a8604) from Ruby 2.2.2 and 2.1.6, both 32 bit.

**Comment by Dahrkael** [comment]
which version? 2.0.0 or 2.0.1? the win32.c errors are fixed with the last pull request.
tested on windows 10 x64 with ruby 2.2 and compiles fine

**Comment by cyberarm** [comment]
0.2.0...
0.2.1 fixes the issue(s). :cake: :tada:
